[project]
name = "actions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.1",
    "django-extensions>=4.1",
]


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["bookstore", "books"]

[tool.setuptools.packages.find]
# ✅ সব অপ্রয়োজনীয় ফোল্ডার exclude করুন
exclude = [
    "actions*",    # 👈 আপনার actions ফোল্ডার
    "cd*",
    "CI_CD*",
    "scripts*",
    "data*",
    "tests*",
    ".github*",
]